include:
  - project: "apps/nuc-subcharts/gitlab-ci"
    ref: "main"
    file:
      - "/publish-subchart.gitlab-ci.yml"

variables:
  CHART_PATH: "./"
  HARBOR_REGISTRY: $REGISTRY_NAME
  HARBOR_PROJECT: "public"